default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: render_rails_development

production:
  <<: *default
  host: aws-0-us-west-1.pooler.supabase.com
  database: postgres
  username: postgres.wyrpppixxamwwhpoayqe
  password: yTHqjoZhs7TxQVNK
